<?php
namespace GDO\DogRSS\Method;

use GDO\Core\GDO_DBException;
use GDO\Core\GDT;
use GDO\Core\Method;
use GDO\DogRSS\GDO_RSSFeed;
use GDO\DogRSS\GDO_RSSItem;

final class CheckFeeds extends Method
{

    public function isCLI(): bool
    {
        return parent::isCLI(); // TODO: Change the autogenerated stub
    }

    public function getCLITrigger(): string
    {
        return 'feeds.check';
    }

    public function isHiddenMethod(): bool
    {
        return true;
    }

    /**
     * @throws GDO_DBException
     */
    public function execute(): GDT
    {
        $sent = $updates = 0;
        $feeds = GDO_RSSFeed::table()->allCached();
        foreach ($feeds as $feed)
        {
            if (!$feed->isDeleted())
            {
                list($u, $s) = $feed->checkFeed(true);
                $updates += $u;
                $sent += $s;
            }
        }
        return $this->message('msg_feeds_checked', [$updates, $sent]);
    }

}
